name: roll-back-monitor pipeline
on: 
  workflow_dispatch:
    inputs:
      image_name: 
        description: docker_image to create 
        required: true
      user_name: 
        description: user_name for naming container
        required: true
      HOST:
        description: ip of instance to login
        required: true
jobs:
  login-job:
    runs-on: ubuntu-latest
    steps:
      - name: Rollback containers with simple monitoring
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ inputs.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          timeout: 1800s
          script: |
            cd ~
            
            docker stop ${{ inputs.user_name }} 2>/dev/null || true
            docker rm ${{ inputs.user_name }} 2>/dev/null || true
            docker image prune -a -f
            docker run -dp 80:80 --name ${{ inputs.user_name }} ${{ inputs.image_name }}
