name: roll-back pipeline
on: 
  workflow_dispatch:
    inputs:
      image_name: 
        description: docker_image to create 
        required: true
      user_name: 
        description: user_name for naming container
        required: true
      HOST:
        description: ip of instnace to login
        required: true
jobs:
  login-job:
    runs-on: ubuntu-latest
    steps:
      - name: Exec cmd on remote server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ inputs.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~
            docker stop $(docker ps -q)
            docker rm $(docker ps -a -q)
            docker rm -f $(docker ps -a -q)
            docker run -dp 80:80 --name ${{ inputs.user_name }} ${{ inputs.image_name }}
            docker run -p 9090:9090 prom/prometheus
            docker run -d -p 3000:3000 --name=grafana grafana/grafana-enterprise
